### ISSUE TITLE
BCH support

### ISSUE THREAD

**Issue by OverlordQ** [SjorsO/keys#29]
I started looking at adding BCH support and to split it out like BCH and ETH are, there's a *lot* of duplication for what effectively is a 2 line change.

The balance API just needs set to `https://api.blockchain.info/bch/balance?cors=true&active=` and replace `btc` with `bch` in the links.

**Comment by SjorsO** [comment]
I wanted to add support for BCH keys, but at the time i couldn't find a good api for balance checking. I had no idea blockchain.com offers an api for that too.

Adding BCH support shouldn't be too much work. I'll start working on it soon. Thanks for the tip 😄

**Comment by SjorsO** [comment]
I've changed my mind and decided to stick to only bitcoin and ethereum for now
