### ISSUE TITLE
How to make public?

### ISSUE THREAD

**Issue by WesNz** [SjorsO/keys#35]
Hi

i installed everything correctly with no issues.
But cant seem to figure out how to make this public like keys.lol?
I have setup nginx and all php requirements too.

Is the site available in public?

When i visit my url it shows 404 - not found. I have test a phpinfo.php file and that works fine.

-------------

 DONE  Compiled successfully in 6715ms                                                                                    9:54:02 AM
                                                                                                               Asset      Size             Chunks             Chunk Names
       /css/main.css   404 KiB            /js/app  [emitted]  /js/app
          /js/app.js  87.9 KiB            /js/app  [emitted]  /js/app
 /js/bitcoin-page.js  7.34 KiB   /js/bitcoin-page  [emitted]  /js/bitcoin-page
/js/ethereum-page.js  5.74 KiB  /js/ethereum-page  [emitted]  /js/ethereum-page

**Comment by SjorsO** [comment]
It is a Laravel application, you can find plenty of guides for Laravel development on google.
