### ISSUE TITLE
easy way of testing the mail function?

### ISSUE THREAD

**Issue by WesNz** [SjorsO/keys#36]
Hi

is there an easy way to test the mail function? just want to make sure it actually sends the email

**Comment by SjorsO** [comment]
Sorry, i can't help you with questions like these

**Comment by WesNz** [comment]
MAIL_ENCRYPTION=null   is that referring to ssl/tls 
would this be correct? " MAIL_ENCRYPTION=SSL "

if i were wanting to use ssl
