### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by Zeeko22** [SjorsO/keys#42]
Hi,

Pls can anoyone guide me what can be wrong while installing the last 2 steps.

I installed all but the last steps i get error message message.. I run 5.2.0-kali2-amd64

I wish there was a complete guide to installing it... Seems as i need to do something with mysqldatabase? Can anyone guide me how to finish this installation....

user2@User2:~/keys$ php artisan migrate:fresh

n Connection.php line 664:

SQLSTATE[HY000] [2002] Connection refused (SQL: SHOW FULL TABLES WHERE tabl
e_type = 'BASE TABLE')

In PDOConnection.php line 31:

SQLSTATE[HY000] [2002] Connection refused

In PDOConnection.php line 27:

SQLSTATE[HY000] [2002] Connection refused

**Comment by SjorsO** [comment]
You need a mysql database to run the application. This is standard for Laravel applications.

You can look up guides online on how to set up a Laravel dev environment
