### ISSUE TITLE
auto scan(WITH basket to store keys with btc) and option for max keys per page please

### ISSUE THREAD

**Issue by hitendrapharmacy** [SjorsO/keys#52]
can we able to keep a button for auto scan which saves the balance keys in a basket so we dont have to check all the time for balance and also maximize the number of keys per page like 1k to 5k depends if possible..!!!!

**Comment by SjorsO** [comment]
Keys.lol is a demonstration of how secure bitcoin is. Nobody will ever find anything, no matter how long (or fast) they search. Please watch this video: https://www.youtube.com/watch?v=S9JGmA5_unY&feature=emb_title
