### ISSUE TITLE
Blockchain addresses Balance not working

### ISSUE THREAD

**Issue by webdev86** [SjorsO/keys#56]
Balances are not checked, used or empty addresses do not give any yellow color as you mentioned, try to inspect any page you will see that blockchain is giving an error

I attached a screenshot
![Capture](https://user-images.githubusercontent.com/71932943/95630736-4253ad00-0a7a-11eb-8777-a4de60e5faea.JPG)

**Comment by SjorsO** [comment]
Thank you for reporting this problem.

It looks like the Blockchain.com api that was used for balance checking has changed. The requests now fail due to CORS.

I've tried different API endpoints, but they have the same problem. I've tried looking for a different API to use, but there doesn't seem to be one. Unfortunately I can't fix this problem right now.

**Comment by webdev86** [comment]
Hi, Thank you for your reply. I appreciate it :)

Can I suggest an idea? 
I believe that blockchain has a rate limit where their policy is metered to check a certain number of addresses in a certain amount of time, I tried scripts before where I selected blockchain as API to check addresses balance but all I get is "Too many attempts, rate limit" then they just ban my ip for a while, but what was working for me is something slow but anyway I always appreciate something than Nothing. I sat my timers to check the balances every 2 seconds for every address in a loop, so for the sake of this beautiful work you did, it will be worthless without a solution, when you click on Random for example, you get a list then if you could, you can check the balance, address by address every 2 seconds until the list is finished, since it is only client side, if you try to check the whole list at once, you will get banned, not you, but the IP of the user that is using your site, since the balance check is coming from the user's browser or computer.

**Comment by SjorsO** [comment]
I currently have no idea how to fix this problem
